version: 2
updates:
  - package-ecosystem: npm
    directory: /src/ef-core-commander
    schedule:
      interval: weekly
  - package-ecosystem: nuget
    directory: /test/fixtures/ef-core-commander-sqlite-test
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
